/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { D_WORK_PROGRAM_ADDRESS } from '../programs';

/** JobNotAvailable: Job is not available for acceptance */
export const D_WORK_ERROR__JOB_NOT_AVAILABLE = 0x1770; // 6000
/** JobNotCompleted: Job cannot be completed in current state */
export const D_WORK_ERROR__JOB_NOT_COMPLETED = 0x1771; // 6001
/** JobCannotBeCancelled: Job cannot be cancelled in current state */
export const D_WORK_ERROR__JOB_CANNOT_BE_CANCELLED = 0x1772; // 6002
/** InvalidAmount: Amount can't be negative  */
export const D_WORK_ERROR__INVALID_AMOUNT = 0x1773; // 6003
/** InsufficientBalance: Insufficient balance in sol   */
export const D_WORK_ERROR__INSUFFICIENT_BALANCE = 0x1774; // 6004
/** InvalidStatus: Invalid Status ..  */
export const D_WORK_ERROR__INVALID_STATUS = 0x1775; // 6005
/** Unauthorized: You are not authorized  */
export const D_WORK_ERROR__UNAUTHORIZED = 0x1776; // 6006
/** ConfirmationDeadlineNotPassed: Confirmation deadline not yet passed */
export const D_WORK_ERROR__CONFIRMATION_DEADLINE_NOT_PASSED = 0x1777; // 6007
/** InvalidJudgment: Invalid Judging status */
export const D_WORK_ERROR__INVALID_JUDGMENT = 0x1778; // 6008
/** JobNotInDispute: Job is not in dispute  */
export const D_WORK_ERROR__JOB_NOT_IN_DISPUTE = 0x1779; // 6009
/** JobNotConfirmed: Job is not confirmed by employer  */
export const D_WORK_ERROR__JOB_NOT_CONFIRMED = 0x177a; // 6010
/** JobNotRefundable: Job is not refundable  */
export const D_WORK_ERROR__JOB_NOT_REFUNDABLE = 0x177b; // 6011

export type DWorkError =
  | typeof D_WORK_ERROR__CONFIRMATION_DEADLINE_NOT_PASSED
  | typeof D_WORK_ERROR__INSUFFICIENT_BALANCE
  | typeof D_WORK_ERROR__INVALID_AMOUNT
  | typeof D_WORK_ERROR__INVALID_JUDGMENT
  | typeof D_WORK_ERROR__INVALID_STATUS
  | typeof D_WORK_ERROR__JOB_CANNOT_BE_CANCELLED
  | typeof D_WORK_ERROR__JOB_NOT_AVAILABLE
  | typeof D_WORK_ERROR__JOB_NOT_COMPLETED
  | typeof D_WORK_ERROR__JOB_NOT_CONFIRMED
  | typeof D_WORK_ERROR__JOB_NOT_IN_DISPUTE
  | typeof D_WORK_ERROR__JOB_NOT_REFUNDABLE
  | typeof D_WORK_ERROR__UNAUTHORIZED;

let dWorkErrorMessages: Record<DWorkError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  dWorkErrorMessages = {
    [D_WORK_ERROR__CONFIRMATION_DEADLINE_NOT_PASSED]: `Confirmation deadline not yet passed`,
    [D_WORK_ERROR__INSUFFICIENT_BALANCE]: `Insufficient balance in sol  `,
    [D_WORK_ERROR__INVALID_AMOUNT]: `Amount can't be negative `,
    [D_WORK_ERROR__INVALID_JUDGMENT]: `Invalid Judging status`,
    [D_WORK_ERROR__INVALID_STATUS]: `Invalid Status .. `,
    [D_WORK_ERROR__JOB_CANNOT_BE_CANCELLED]: `Job cannot be cancelled in current state`,
    [D_WORK_ERROR__JOB_NOT_AVAILABLE]: `Job is not available for acceptance`,
    [D_WORK_ERROR__JOB_NOT_COMPLETED]: `Job cannot be completed in current state`,
    [D_WORK_ERROR__JOB_NOT_CONFIRMED]: `Job is not confirmed by employer `,
    [D_WORK_ERROR__JOB_NOT_IN_DISPUTE]: `Job is not in dispute `,
    [D_WORK_ERROR__JOB_NOT_REFUNDABLE]: `Job is not refundable `,
    [D_WORK_ERROR__UNAUTHORIZED]: `You are not authorized `,
  };
}

export function getDWorkErrorMessage(code: DWorkError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (dWorkErrorMessages as Record<DWorkError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isDWorkError<TProgramErrorCode extends DWorkError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    D_WORK_PROGRAM_ADDRESS,
    code
  );
}
