/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { D_WORK_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const REPORT_JOB_BY_EMPLOYER_DISCRIMINATOR = new Uint8Array([
  65, 254, 34, 234, 192, 155, 10, 81,
]);

export function getReportJobByEmployerDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REPORT_JOB_BY_EMPLOYER_DISCRIMINATOR
  );
}

export type ReportJobByEmployerInstruction<
  TProgram extends string = typeof D_WORK_PROGRAM_ADDRESS,
  TAccountEmployer extends string | AccountMeta<string> = string,
  TAccountJob extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountEmployer extends string
        ? WritableSignerAccount<TAccountEmployer> &
            AccountSignerMeta<TAccountEmployer>
        : TAccountEmployer,
      TAccountJob extends string ? WritableAccount<TAccountJob> : TAccountJob,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ReportJobByEmployerInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ReportJobByEmployerInstructionDataArgs = {};

export function getReportJobByEmployerInstructionDataEncoder(): FixedSizeEncoder<ReportJobByEmployerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: REPORT_JOB_BY_EMPLOYER_DISCRIMINATOR,
    })
  );
}

export function getReportJobByEmployerInstructionDataDecoder(): FixedSizeDecoder<ReportJobByEmployerInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getReportJobByEmployerInstructionDataCodec(): FixedSizeCodec<
  ReportJobByEmployerInstructionDataArgs,
  ReportJobByEmployerInstructionData
> {
  return combineCodec(
    getReportJobByEmployerInstructionDataEncoder(),
    getReportJobByEmployerInstructionDataDecoder()
  );
}

export type ReportJobByEmployerInput<
  TAccountEmployer extends string = string,
  TAccountJob extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  employer: TransactionSigner<TAccountEmployer>;
  job: Address<TAccountJob>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getReportJobByEmployerInstruction<
  TAccountEmployer extends string,
  TAccountJob extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof D_WORK_PROGRAM_ADDRESS,
>(
  input: ReportJobByEmployerInput<
    TAccountEmployer,
    TAccountJob,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): ReportJobByEmployerInstruction<
  TProgramAddress,
  TAccountEmployer,
  TAccountJob,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? D_WORK_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    employer: { value: input.employer ?? null, isWritable: true },
    job: { value: input.job ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.employer),
      getAccountMeta(accounts.job),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getReportJobByEmployerInstructionDataEncoder().encode({}),
    programAddress,
  } as ReportJobByEmployerInstruction<
    TProgramAddress,
    TAccountEmployer,
    TAccountJob,
    TAccountSystemProgram
  >);
}

export type ParsedReportJobByEmployerInstruction<
  TProgram extends string = typeof D_WORK_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    employer: TAccountMetas[0];
    job: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: ReportJobByEmployerInstructionData;
};

export function parseReportJobByEmployerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedReportJobByEmployerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      employer: getNextAccount(),
      job: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getReportJobByEmployerInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
